# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 12:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banji', models.CharField(max_length=50, verbose_name='班级')),
            ],
            options={
                'verbose_name_plural': '班级',
                'verbose_name': '班级',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=50, verbose_name='学院')),
            ],
            options={
                'verbose_name_plural': '学院',
                'verbose_name': '学院',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmen', models.CharField(max_length=50, verbose_name='系别')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RGPY.College', verbose_name='所属学院')),
            ],
            options={
                'verbose_name_plural': '系别',
                'verbose_name': '系别',
            },
        ),
        migrations.CreateModel(
            name='Stuent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_banji_admin', models.BooleanField(default=False, help_text='是否是班级管理员.')),
                ('score', models.PositiveSmallIntegerField(verbose_name='已获时长')),
                ('banji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RGPY.Banji', verbose_name='所属班级')),
            ],
            options={
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='banji',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RGPY.Department', verbose_name='所属系别'),
        ),
    ]
