# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RGPY', '0002_banji_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.PositiveSmallIntegerField(verbose_name='需要的人数')),
                ('start_time', models.DateField(default=django.utils.timezone.now, verbose_name='开始报名时间')),
                ('end_time', models.DateField(default=django.utils.timezone.now, verbose_name='报名结束时间')),
                ('task_time', models.DateField(verbose_name='任务完成时间')),
                ('score', models.PositiveSmallIntegerField(default=2, verbose_name='时长')),
                ('remark', models.TextField(verbose_name='备注')),
                ('promulgator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布者')),
            ],
        ),
        migrations.AlterModelOptions(
            name='banji',
            options={'ordering': ['-grade'], 'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['username'], 'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AlterField(
            model_name='student',
            name='is_banji_admin',
            field=models.BooleanField(default=False, help_text='是否是班级管理员.', verbose_name='是否是班级管理员'),
        ),
    ]
