# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0002_banji_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departmen',
            new_name='department',
        ),
    ]
