# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0003_auto_20170130_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banji',
            name='phone',
        ),
        migrations.AddField(
            model_name='stuent',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='用户手机'),
        ),
    ]
