# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0003_auto_20170305_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='COS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.PositiveSmallIntegerField(choices=[(1, '个人任务'), (2, '班级任务'), (3, '系任务'), (4, '院任务')], default=2, verbose_name='任务类别')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='service_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='RGPY.COS', verbose_name='任务类型'),
        ),
    ]
