# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0004_auto_20170130_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stuent',
            new_name='Student',
        ),
    ]
