# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0004_auto_20170305_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cos',
            options={'verbose_name': '管理员', 'verbose_name_plural': '管理员'},
        ),
        migrations.AlterField(
            model_name='cos',
            name='service',
            field=models.PositiveSmallIntegerField(verbose_name='任务类别'),
        ),
    ]
