# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0005_auto_20170305_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cos',
            name='service',
            field=models.CharField(max_length=32, verbose_name='任务类别'),
        ),
    ]
