# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0006_auto_20170130_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='已获时长'),
        ),
    ]
