# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0007_auto_20170130_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='banji',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='RGPY.Banji', verbose_name='所属班级'),
        ),
    ]
