# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0008_auto_20170130_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banji',
            name='department',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='RGPY.Department', verbose_name='所属系别'),
        ),
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='RGPY.College', verbose_name='所属学院'),
        ),
    ]
