# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0008_auto_20170305_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='task_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='任务完成时间'),
        ),
    ]
