# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0010_auto_20170307_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approval', models.BooleanField(default=False, verbose_name='是否批准')),
                ('add_score', models.BooleanField(default=False, verbose_name='是否增加时长')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RGPY.Student', verbose_name='申请人')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ('-task_time', 'end_time', '-id'), 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AddField(
            model_name='taskapply',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RGPY.Mission', verbose_name='任务'),
        ),
    ]
