# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0015_auto_20170313_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddScoreApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, default=2, verbose_name='申请的时长')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='提出申请的时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RGPY.Student', verbose_name='申请人')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('task_type', models.CharField(max_length=20, verbose_name='任务类型')),
                ('taskDate', models.DateField(auto_now_add=True, verbose_name='获得分值的时间')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouruser_id', to='RGPY.OurUser', verbose_name='审核人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='RGPY.Student', verbose_name='获得时长的学生')),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='mission',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=2, verbose_name='时长'),
        ),
    ]
