# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0016_auto_20170316_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='addscoreapply',
            name='flag',
            field=models.NullBooleanField(verbose_name='是否被批准'),
        ),
    ]
