# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGPY', '0017_addscoreapply_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='addscoreapply',
            name='remark',
            field=models.TextField(default='', verbose_name='备注'),
        ),
    ]
